CREATE TABLE `user` (
	`id` BIGINT(20) UNSIGNED NOT NULL AUTO_INCREMENT,
	`name` VARCHAR(32) NULL DEFAULT NULL,
	`SURNAME` VARCHAR(32) NULL DEFAULT NULL,
	`ADR` VARCHAR(32) NULL DEFAULT NULL,
	`phone` VARCHAR(50) NULL DEFAULT NULL,
	`email` VARCHAR(32) NULL DEFAULT NULL,
	`filename` VARCHAR(124) NULL DEFAULT NULL,
	`_file` BLOB NULL,
	`state` INT(11) NULL DEFAULT NULL,
	PRIMARY KEY (`id`)
)
COLLATE='utf8mb4_0900_ai_ci'
ENGINE=InnoDB
;
