CREATE TABLE `user_skill` (
	`ID` BIGINT(20) NOT NULL AUTO_INCREMENT,
	`USER_ID` BIGINT(20) NOT NULL DEFAULT '0',
	`PHASE_ID` BIGINT(20) NOT NULL DEFAULT '0',
	`NAME` VARCHAR(128) NOT NULL DEFAULT '0',
	`LEVEL` BIGINT(20) NOT NULL DEFAULT '0',
	`COMMENTS` TEXT NULL,
	PRIMARY KEY (`ID`)
)
COLLATE='latin1_swedish_ci'
ENGINE=InnoDB
;