CREATE TABLE `user_skill` (
	`ID` INT(5) NOT NULL AUTO_INCREMENT,
	`USER_ID` INT(5) NOT NULL DEFAULT '0',
	`PHASE_ID` INT(5) NOT NULL DEFAULT '0',
	`NAME` VARCHAR(128) NOT NULL DEFAULT '0',
	`LEVEL` BIT(2) NOT NULL DEFAULT b'0',
	`COMMENTS` TEXT NULL,
	PRIMARY KEY (`ID`)
)
COLLATE='latin1_swedish_ci'
ENGINE=InnoDB
;