CREATE TABLE `user_skill` (
	`ID` BIGINT(20) NOT NULL AUTO_INCREMENT,
	`USER_ID` BIGINT(20) UNSIGNED NOT NULL,
	`PHASE_ID` BIGINT(20) UNSIGNED NOT NULL,
	`NAME` VARCHAR(128) NOT NULL,
	`LEVEL` BIGINT(20) NOT NULL DEFAULT '0',
	`COMMENTS` VARCHAR(1024) NULL DEFAULT NULL,
	PRIMARY KEY (`ID`),
	INDEX `FK_USER_SKILL_USER_ID` (`USER_ID`),
	INDEX `FK_USER_SKILL_PHASE_ID` (`PHASE_ID`),
	CONSTRAINT `FK_USER_SKILL_PHASE_ID` FOREIGN KEY (`PHASE_ID`) REFERENCES `phase` (`id`),
	CONSTRAINT `FK_USER_SKILL_USER_ID` FOREIGN KEY (`USER_ID`) REFERENCES `user` (`id`)
)
ENGINE=InnoDB
AUTO_INCREMENT=2
;
