CREATE TABLE `user` (
	`id` INT(11) NULL DEFAULT NULL,
	`name` VARCHAR(32) NULL DEFAULT NULL,
	`SURNAME` VARCHAR(32) NULL DEFAULT NULL,
	`ADR` VARCHAR(32) NULL DEFAULT NULL,
	`phone` INT(11) NULL DEFAULT NULL,
	`email` VARCHAR(32) NULL DEFAULT NULL,
	`filename` BLOB NULL,
	`_file` BLOB NULL,
	`state` INT(11) NULL DEFAULT NULL
)
COLLATE='utf8mb4_0900_ai_ci'
ENGINE=InnoDB
;
